<?php

namespace Ndrm\ConceptBundle\Repository\Param;

use Doctrine\ORM\EntityRepository;

/**
 * ParamHtmlInputTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamRepository extends \Doctrine\ORM\EntityRepository {

    function findByCatWithInputTypeTitle($concetCatId) {
        $qb = $this->createQueryBuilder("paramListing");
        $userRoles = $qb->select("concept_params.name"
                . ",concept_params.title"
                . ",concept_params.description"
                ."concept_param_input_types.title"
                )
                ->from("concept_params", "concept_params")
                ->innerJoin("concept_params"
                        , "concept_param_input_types"
                        , "concept_param_input_types"//alias name
                        , "concept_param_input_types.id_concept_param_input_types=concept_params.id_concept_param_input_types")
                ->innerJoin("concept_params"
                        , "concept_categories"
                        , "concept_categories"//alias name
                        , "concept_categories.id_concept_categories=concept_params.id_concept_categories")
                ->where("concept_categories.id_concept_categories=?1")
                ->orderBy("concept_params.title")
                ->setParameter(1, $concetCatId)
        ;
//        dump($userRoles);
        return $userRoles;
    }

}
