<?php

namespace Ndrm\AuthBundle\Repository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository {

    public function getAllMonitpringsAndTheirIds() {
        $qb = $this->createQueryBuilder("getAllMonitpringsAndTheirIds");
        $allRolesAndIds = $qb->select("r.id,r.monitoring")
                ->from("NdrmAuthBundle:Role", "r")
                ->orderBy("r.monitoring", "ASC")
                ->distinct("r.id")
                ->getQuery()
                ->getArrayResult()
        ;
        return $allRolesAndIds;
    }

}
