<?php

namespace Ndrm\AuthBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository {

    public function getUsernameByIdUsers($idUsers) {
        $qb = $this->createQueryBuilder("getUsernameByIdUsers");
        $user = $qb->select("u.username")
                ->from("users", "u")
                ->where("users.id_users=?1")
                ->setParameter(1, $idUsers)
                ->getSingleResult();
        $username = $user["username"];
        return $username;
    }

}
