ndrm_location:
    resource: "@NdrmLocationBundle/Controller/"
    type:     annotation
    prefix:   /location

logout:
    path: /logout
ndrm_my_tests:
    resource: "@NdrmMyTestsBundle/Controller/"
    type:     annotation
    prefix:   /

ndrm_entity_tests:
    resource: "@NdrmEntityTestsBundle/Controller/"
    type:     annotation
    prefix:   /

ndrm_auth:
    resource: "@NdrmAuthBundle/Controller/"
    type: annotation
    prefix:   /auth

ndrm_concept:
    resource: "@NdrmConceptBundle/Controller/"
    type:     annotation
    prefix:   /concept

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
