ndrm_auth:
    resource: "@NdrmAuthBundle/Controller/"
    type: annotation
    prefix:   /auth

concept:
    resource: "@ConceptBundle/Controller/"
    type:     annotation
    prefix:   /concept

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
