<?php

namespace ParamBundle\Repository;

/**
 * ParamHtmlInputTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamInputTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
