<?php

namespace ParamBundle\Repository;

/**
 * ParamTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamValueTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
