<?php

namespace Ndrm\ConceptBundle\Repository\Param\Input;

use Doctrine\ORM\EntityRepository;

/**
 * ParamHtmlInputTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRepository extends \Doctrine\ORM\EntityRepository {
    
}
